---
tiers:
    -
        name: features
        order: 2
        ci_loop: '(daily)|(weekly)'
        description: >-
            Test suites from feature projects
            integrated in functest
        testcases:
            -
                case_name: parser-basics
                project_name: parser
                criteria: 100
                blocking: false
                description: >-
                    Test suite from Parser project.
                dependencies:
                    installer: ''
                    scenario: '^((?!bgpvpn|noha).)*$'
                run:
                    module: 'functest.core.feature'
                    class: 'BashFeature'
                    args:
                        cmd: 'cd /src/nfv-parser/tests && ./functest_run.sh'
