tiers:
    -
        name: features
        order: 2
        ci_loop: '(daily)|(weekly)'
        description : >-
            Test suites from feature projects
            integrated in functest
        testcases:
            -
                case_name: promise
                project_name: promise
                criteria: 100
                blocking: false
                description: >-
                    Test suite from Promise project.
                dependencies:
                    installer: '(fuel)|(joid)'
                    scenario: ''
                run:
                    module: 'functest.core.feature'
                    class: 'BashFeature'
                    args:
                        cmd: 'run_promise_tests.py'

            -
                case_name: bgpvpn
                project_name: sdnvpn
                criteria: 100
                blocking: false
                description: >-
                    Test suite from SDNVPN project.
                dependencies:
                    installer: '(fuel)|(apex)|(netvirt)'
                    scenario: 'bgpvpn'
                run:
                    module: 'functest.core.feature'
                    class: 'BashFeature'
                    args:
                        cmd: 'run_sdnvpn_tests.py'

            -
                case_name: security_scan
                enabled: false
                project_name: securityscanning
                criteria: 100
                blocking: false
                description: >-
                    Simple Security Scan
                dependencies:
                    installer: 'apex'
                    scenario: '^((?!fdio).)*$'
                run:
                    module: 'functest.core.feature'
                    class: 'BashFeature'
                    args:
                        cmd: '. /home/opnfv/functest/conf/stackrc && security_scan --config /usr/local/etc/securityscanning/config.ini'

            -
                case_name: functest-odl-sfc
                enabled: false
                project_name: sfc
                criteria: 100
                blocking: false
                description: >-
                    Test suite for odl-sfc to test two chains and two SFs
                dependencies:
                    installer: '(apex)|(fuel)'
                    scenario: 'odl_l2-sfc'
                run:
                    module: 'functest.core.feature'
                    class: 'BashFeature'
                    args:
                        cmd: 'run_sfc_tests.py'

            -
                case_name: domino-multinode
                enabled: false
                project_name: domino
                criteria: 100
                blocking: false
                description: >-
                    Test suite from Domino project.
                dependencies:
                    installer: ''
                    scenario: ''
                run:
                    module: 'functest.core.feature'
                    class: 'BashFeature'
                    args:
                        cmd: 'cd /src/domino && ./tests/run_multinode.sh'

            -
                case_name: barometercollectd
                enabled: true
                project_name: barometer
                criteria: 100
                blocking: false
                description: >-
                    Test suite for the Barometer project. Separate tests verify
                    the proper configuration and basic functionality of all the
                    collectd plugins as described in the Project Release Plan
                dependencies:
                    installer: 'apex'
                    scenario: 'bar'
                run:
                     module: 'baro_tests.barometer'
                     class: 'BarometerCollectd'
