tiers:
    -
        name: vnf
        order: 4
        ci_loop: '(daily)|(weekly)'
        description : >-
            Collection of VNF test cases.
        testcases:
            -
                case_name: cloudify_ims
                project_name: functest
                criteria: 80
                blocking: false
                description: >-
                    This test case deploys an OpenSource vIMS solution from Clearwater
                    using the Cloudify orchestrator. It also runs some signaling traffic.
                dependencies:
                    installer: ''
                    scenario: 'os-nosdn-nofeature-ha'
                run:
                    module: 'functest.opnfv_tests.vnf.ims.cloudify_ims'
                    class: 'CloudifyIms'

            -
                case_name: vyos_vrouter
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case is vRouter testing.
                dependencies:
                    installer: ''
                    scenario: 'os-nosdn-nofeature-ha'
                run:
                    module: 'functest.opnfv_tests.vnf.router.cloudify_vrouter'
                    class: 'CloudifyVrouter'

            -
                case_name: orchestra_openims
                project_name: orchestra
                criteria: 100
                blocking: false
                description: >-
                    OpenIMS VNF deployment with Open Baton (Orchestra)
                dependencies:
                    installer: 'daisy'
                    scenario: 'os-nosdn-nofeature-ha'
                run:
                    module: 'functest.opnfv_tests.vnf.ims.orchestra_openims'
                    class: 'OpenImsVnf'

            -
                case_name: orchestra_clearwaterims
                project_name: orchestra
                criteria: 100
                blocking: false
                description: >-
                    ClearwaterIMS VNF deployment with Open Baton (Orchestra)
                dependencies:
                    installer: 'daisy'
                    scenario: 'os-nosdn-nofeature-ha'
                run:
                    module: 'functest.opnfv_tests.vnf.ims.orchestra_clearwaterims'
                    class: 'ClearwaterImsVnf'
