---
tiers:
    -
        name: vnf
        order: 4
        ci_loop: '(daily)|(weekly)'
        description: >-
            Collection of VNF test cases.
        testcases:
            -
                case_name: cloudify_ims
                project_name: functest
                criteria: 80
                blocking: false
                description: >-
                    This test case deploys an OpenSource vIMS solution from
                    Clearwater using the Cloudify orchestrator. It also runs
                    some signaling traffic.
                dependencies:
                    installer: ''
                    scenario: 'os-nosdn-nofeature-ha'
                run:
                    module: 'functest.opnfv_tests.vnf.ims.cloudify_ims'
                    class: 'CloudifyIms'

            -
                case_name: vyos_vrouter
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case is vRouter testing.
                dependencies:
                    installer: ''
                    scenario: 'os-nosdn-nofeature-ha'
                run:
                    module: 'functest.opnfv_tests.vnf.router.cloudify_vrouter'
                    class: 'CloudifyVrouter'

            -
                case_name: orchestra_openims
                project_name: orchestra
                criteria: 100
                blocking: false
                description: >-
                    OpenIMS VNF deployment with Open Baton (Orchestra)
                dependencies:
                    installer: '^((?!compass|fuel).)*$'
                    scenario: 'os-nosdn-nofeature-ha'
                run:
                    module: 'functest.opnfv_tests.vnf.ims.orchestra_openims'
                    class: 'OpenImsVnf'

            -
                case_name: orchestra_clearwaterims
                project_name: orchestra
                criteria: 100
                blocking: false
                description: >-
                    ClearwaterIMS VNF deployment with Open Baton (Orchestra)
                dependencies:
                    installer: '^((?!compass|fuel).)*$'
                    scenario: 'os-nosdn-nofeature-ha'
                run:
                    module:
                        'functest.opnfv_tests.vnf.ims.orchestra_clearwaterims'
                    class: 'ClearwaterImsVnf'

            -
                case_name: juju_epc
                enabled: true
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    vEPC validation with Juju as VNF manager and ABoT as test
                    executor.
                dependencies:
                    installer: ''
                    scenario: 'os-nosdn-nofeature-ha'
                run:
                    module: 'functest.opnfv_tests.vnf.epc.juju_epc'
                    class: 'JujuEpc'
