---
tiers:
    -
        name: vnf
        order: 4
        ci_loop: '(daily)|(weekly)'
        description: >-
            Collection of VNF test cases.
        testcases:
            -
                case_name: cloudify
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case deploys the Cloudify orchestrator.
                dependencies:
                    installer: ''
                    scenario: 'os-.*-nofeature-.*ha'
                run:
                    module: 'functest.core.cloudify'
                    class: 'Cloudify'
            -
                case_name: cloudify_ims
                project_name: functest
                criteria: 80
                blocking: false
                description: >-
                    This test case deploys an OpenSource vIMS solution from
                    Clearwater using the Cloudify orchestrator. It also runs
                    some signaling traffic.
                dependencies:
                    installer: ''
                    scenario: 'os-.*-nofeature-.*ha'
                run:
                    module: 'functest.opnfv_tests.vnf.ims.cloudify_ims'
                    class: 'CloudifyIms'

            -
                case_name: vyos_vrouter
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case is vRouter testing.
                dependencies:
                    installer: ''
                    scenario: 'os-.*-nofeature-.*ha'
                run:
                    module: 'functest.opnfv_tests.vnf.router.cloudify_vrouter'
                    class: 'CloudifyVrouter'

            -
                case_name: juju_epc
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    vEPC validation with Juju as VNF manager and ABoT as test
                    executor.
                dependencies:
                    installer: ''
                    scenario: 'os-.*-nofeature-.*ha'
                run:
                    module: 'functest.opnfv_tests.vnf.epc.juju_epc'
                    class: 'JujuEpc'
