general:
    dir:
        # Relative to the path where the repo is cloned:
        vping:             functest/opnfv_tests/openstack/vping
        dir_odl:           functest/opnfv_tests/sdn/odl
        rally:             functest/opnfv_tests/openstack/rally
        tempest_cases:     functest/opnfv_tests/openstack/tempest/custom_tests
        onos:              functest/opnfv_tests/sdn/onos/teston
        onos_sfc:          functest/opnfv_tests/sdn/onos/sfc

        # Absolute path
        home:               /home/opnfv
        repos:              /home/opnfv/repos
        repo_functest:      /root/dev/git/functest-root/functest
        dir_repo_rally:     /root/dev/git/rally
        repo_tempest:       /root/dev/git/tempest
        dir_repo_releng:    /root/dev/git/releng
        repo_vims_test:     /root/dev/git/vnfs/vims-test
        repo_sdnvpn:        /root/dev/git/sdnvpn
        repo_sfc:           /root/dev/git/sfc
        repo_onos:          /root/dev/git/onos
        repo_promise:       /root/dev/git/promise
        repo_netready:      /root/dev/git/netready
        repo_barometer:     /root/dev/git/barometer
        repo_doctor:        /root/dev/git/doctor
        repo_copper:        /root/dev/git/copper
        repo_parser:        /root/dev/git/parser
        repo_domino:        /root/dev/git/domino
        repo_snaps:         /root/dev/git/snaps
        repo_opera:         /root/dev/git/opera
        repo_fds:           /root/dev/git/fds
        repo_securityscan:  /root/dev/git/securityscanning
        repo_vrouter:       /root/dev/git/vnfs/vrouter
        functest:           /home/opnfv/functest
        functest_test:      /root/dev/git/functest-root/functest/opnfv_tests
        results:            /home/opnfv/functest/results
        functest_logging_cfg:   /root/dev/git/functest-root/functest/ci/logging.json
        functest_conf:      /home/opnfv/functest/conf
        functest_data:      /home/opnfv/functest/data
        ims_data:           /home/opnfv/functest/data/ims/
        rally_inst:         /home/opnfv/.rally
        repo_kingbird:      /root/dev/git/kingbird
        refstack_client:    /root/dev/git/refstack-client

    openstack:
        creds: /root/dev/git/functest-root/functest/conf/openstack.creds
        snapshot_file: /root/dev/git/functest-root/functest/conf/openstack_snapshot.yaml

        image_name: Cirros-0.3.5
        image_name_alt: Cirros-0.3.5-1
        image_file_name:  cirros-0.3.5-x86_64-disk.img
        image_url: http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
        image_user: cirros
        image_disk_format:  qcow2
        image_username:  cirros
        image_password:  cubswin:)

        flavor_name: opnfv_flavor
        flavor_name_alt: opnfv_flavor_1
        flavor_ram: 512
        flavor_disk: 1
        flavor_vcpus: 1

        # Private network for functest. Will be created by config_functest.py
        neutron_private_net_name: functest-net
        neutron_private_subnet_name: functest-subnet
        neutron_private_subnet_cidr: 192.168.120.0/24
        neutron_private_subnet_start: 192.168.120.2
        neutron_private_subnet_end: 192.168.120.254
        neutron_private_subnet_gateway: 192.168.120.254
        neutron_router_name: functest-router

    functest:
        testcases_yaml: /root/dev/git/functest-root/functest/functest/ci/testcases.yaml

healthcheck:
    disk_image: /root/dev/git/functest-root/data/cirros-0.3.5-x86_64-disk.img
    disk_format: qcow2
    wait_time: 60

snaps:
    use_keystone: True
    use_floating_ips: False

vping:
    ping_timeout:   200
    vm_flavor: m1.tiny # adapt to your environment
    vm_name_1: opnfv-vping-1
    vm_name_2: opnfv-vping-2
    image_name: functest-vping
    private_net_name: vping-net
    private_subnet_name: vping-subnet
    private_subnet_cidr: 192.168.130.0/24
    router_name: vping-router
    sg_name: vPing-sg
    sg_desc: Security group for vPing test case
    keypair_name: vPing-keypair
    keypair_priv_file: /tmp/vPing-keypair
    keypair_pub_file: /tmp/vPing-keypair.pub
    vm_boot_timeout: 180
    vm_delete_timeout: 100
    vm_ssh_connect_timeout: 60
    cleanup_objects: True
    unique_names: True

onos_sfc:
    image_base_url: http://artifacts.opnfv.org/sfc/demo
    image_name: TestSfcVm
    image_file_name: firewall_block_image.img

tempest:
    deployment_name: opnfv-tempest
    identity:
        tenant_name: tempest
        tenant_description: Tenant for Tempest test suite
        user_name: tempest
        user_password: tempest
    validation:
        ssh_timeout: 130
    object_storage:
        operator_role: SwiftOperator
    private_net_name: tempest-net
    private_subnet_name: tempest-subnet
    private_subnet_cidr: 192.168.150.0/24
    router_name: tempest-router
    use_custom_images: False
    use_custom_flavors: False
    volume_device_name: vdc

rally:
    deployment_name: opnfv-rally
    network_name: rally-net
    subnet_name: rally-subnet
    subnet_cidr: 192.168.140.0/24
    router_name: rally-router

refstack:
    tempest_conf_path: openstack/refstack_client/tempest.conf
    defcore_list: openstack/refstack_client/defcore.txt

vnf:
    aaa:
        tenant_name: aaa
        tenant_description: Freeradius server
        tenant_images: {}
    juju_epc:
        tenant_name: epc
        tenant_description: OAI EPC deployed with Juju
        tenant_images: {}
    cloudify_ims:
        tenant_name: cloudify_ims
        tenant_description: vIMS
        config: cloudify_ims.yaml
    orchestra_ims:
        tenant_name: orchestra_ims
        tenant_description: ims deployed with openbaton
        config: orchestra_ims.yaml
    opera_ims:
        tenant_name: opera_ims
        tenant_description: ims deployed with open-o

ONOS:
    general:
        onosbench_username: 'root'
        onosbench_password: 'root'
        onoscli_username: 'root'
        onoscli_password: 'root'
        runtimeout: 300
    environment:
        OCT: '10.20.0.1'
        OC1: '10.20.0.7'
        OC2: '10.20.0.7'
        OC3: '10.20.0.7'
        OCN: '10.20.0.4'
        OCN2: '10.20.0.5'
        installer_master: '10.20.0.2'
        installer_master_username: 'root'
        installer_master_password: 'r00tme'
multisite:
    fuel:
        installer_username: 'root'
        installer_password: 'r00tme'
    compass:
        installer_username: 'root'
        installer_password: 'root'
        multisite_controller_ip: '10.1.0.50'
promise:
    tenant_name: promise
    tenant_description: promise Functionality Testing
    user_name: promiser
    user_pwd: test
    image_name: promise-img
    flavor_name: promise-flavor
    flavor_vcpus: 1
    flavor_ram: 128
    flavor_disk: 0
    network_name: promise-net
    subnet_name: promise-subnet
    subnet_cidr: 192.168.121.0/24
    router_name: promise-router

example:
    vm_name: example-vm
    flavor: m1.small
    image_name: functest-example-vm
    private_net_name: example-net
    private_subnet_name: example-subnet
    private_subnet_cidr: 192.168.170.0/24
    router_name: example-router
    sg_name: example-sg
    sg_desc: Example Security group

results:
    # you can also set a dir (e.g. /home/opnfv/db) to dump results
    # test_db_url: file:///home/opnfv/db
    test_db_url: http://testresults.opnfv.org/test/api/v1
