---
lxd:
    general:
        openstack:
            image_name: Cirros-0.4.0
            image_file_name: cirros-0.4.0-x86_64-lxc.tar.gz
            image_disk_format: raw

fdio:
    general:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        image_properties: {'hw_mem_page_size':'large'}
        openstack:
            flavor_ram: 1024
    snaps:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
    vmready1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
    vmready2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
    singlevm1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
    singlevm2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}

ovs:
    general:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        image_properties: {'hw_mem_page_size':'large'}
        openstack:
            flavor_ram: 1024
    snaps:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
    vmready1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
    vmready2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
    singlevm1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
    singlevm2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
