---
os:
    vmready1:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    vmready2:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    singlevm1:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    singlevm2:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    vping_ssh:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    vping_userdata:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    cinder_test:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    tempest_smoke:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    tempest_neutron:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    refstack_defcore:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    patrole:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    vmtp:
        image:
            /home/opnfv/functest/images/ubuntu-14.04-server-cloudimg-arm64-uefi1.img

    neutron_trunk:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    networking-bgpvpn:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    networking-sfc:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    barbican:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    tempest_full:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    tempest_scenario:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    rally_sanity:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    rally_full:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    rally_jobs:
        image: /home/opnfv/functest/images/cirros-0.4.0-aarch64-disk.img

    tempest:
        use_custom_flavors: 'True'
