---
lxd:
    general:
        openstack:
            image_name: Cirros-0.4.0
            image_file_name: cirros-0.4.0-x86_64-lxc.tar.gz
            image_disk_format: raw

fdio:
    general:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        image_properties: {'hw_mem_page_size':'large'}
        openstack:
            flavor_ram: 1024
    snaps:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
    vping_ssh:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vping_userdata:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_smoke_serial:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    refstack_defcore:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    patrole:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    neutron_trunk:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_full_parallel:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_sanity:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_full:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    cloudify_ims:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    vyos_vrouter:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    juju_epc:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}

ovs:
    general:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        image_properties: {'hw_mem_page_size':'large'}
        openstack:
            flavor_ram: 1024
    snaps:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
    vping_ssh:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vping_userdata:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_smoke_serial:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    refstack_defcore:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    patrole:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    neutron_trunk:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_full_parallel:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_sanity:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_full:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    cloudify_ims:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    vyos_vrouter:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
    juju_epc:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        flavor_alt_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        extra_alt_properties: {'hw_mem_page_size':'large'}
