---
lxd:
    general:
        openstack:
            image_name: Cirros-0.4.0
            image_file_name: cirros-0.4.0-x86_64-lxc.tar.gz
            image_disk_format: raw

fdio:
    general:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        image_properties: {'hw_mem_page_size':'large'}
        openstack:
            flavor_ram: 1024
    snaps:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
    vmready1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vmready2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    singlevm1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    singlevm2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vping_ssh:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vping_userdata:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    cinder_test:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_smoke_serial:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    refstack_defcore:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    patrole:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    shaker:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    neutron_trunk:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    barbican:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_full_parallel:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_sanity:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_full:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024

ovs:
    general:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        image_properties: {'hw_mem_page_size':'large'}
        openstack:
            flavor_ram: 1024
    snaps:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
    vmready1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vmready2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    singlevm1:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    singlevm2:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vping_ssh:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    vping_userdata:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    cinder_test:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_smoke_serial:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    refstack_defcore:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    patrole:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    shaker:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    neutron_trunk:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    barbican:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    tempest_full_parallel:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_sanity:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
    rally_full:
        flavor_extra_specs: {'hw:mem_page_size':'large'}
        extra_properties: {'hw_mem_page_size':'large'}
        flavor_ram: 1024
