---
gsma:
    tempest_smoke:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    tempest_neutron:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    refstack_compute:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    refstack_object:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    refstack_platform:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    patrole:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    vmtp:
        flavor_ram: 2048
        flavor_vcpus: 1
        flavor_disk: 40
    shaker:
        flavor_ram: 2048
        flavor_vcpus: 1
        flavor_disk: 40
    neutron_trunk:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    networking-bgpvpn:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    networking-sfc:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    barbican:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    tempest_full:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    tempest_scenario:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    rally_sanity:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    rally_full:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    rally_jobs:
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    cloudify:
        flavor_ram: 4096
        flavor_vcpus: 2
        flavor_disk: 40
    cloudify_ims:
        flavor_ram: 4096
        flavor_vcpus: 2
        flavor_disk: 40
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    heat_ims:
        flavor_ram: 2048
        flavor_vcpus: 1
        flavor_disk: 40
    vyos_vrouter:
        flavor_ram: 4096
        flavor_vcpus: 2
        flavor_disk: 40
        flavor_alt_ram: 2048
        flavor_alt_vcpus: 1
        flavor_alt_disk: 40
    juju_epc:
        flavor_ram: 2048
        flavor_vcpus: 1
        flavor_disk: 40
        flavor_alt_ram: 4096
        flavor_alt_vcpus: 2
        flavor_alt_disk: 40

fdio:
    vmready1:
        flavor_ram: 1024
    vmready2:
        flavor_ram: 1024
    singlevm1:
        flavor_ram: 1024
    singlevm2:
        flavor_ram: 1024
    vping_ssh:
        flavor_ram: 1024
    vping_userdata:
        flavor_ram: 1024
    cinder_test:
        flavor_ram: 1024
    tempest_smoke:
        flavor_ram: 1024
    tempest_neutron:
        flavor_ram: 1024
    refstack_compute:
        flavor_ram: 1024
    refstack_object:
        flavor_ram: 1024
    refstack_platform:
        flavor_ram: 1024
    patrole:
        flavor_ram: 1024
    vmtp:
        flavor_ram: 2048
    shaker:
        flavor_ram: 1024
    neutron_trunk:
        flavor_ram: 1024
    networking-bgpvpn:
        flavor_ram: 1024
    networking-sfc:
        flavor_ram: 1024
    barbican:
        flavor_ram: 1024
    tempest_full:
        flavor_ram: 1024
    tempest_scenario:
        flavor_ram: 1024
    rally_sanity:
        flavor_ram: 1024
    rally_full:
        flavor_ram: 1024
    rally_jobs:
        flavor_ram: 1024

ovs:
    vmready1:
        flavor_ram: 1024
    vmready2:
        flavor_ram: 1024
    singlevm1:
        flavor_ram: 1024
    singlevm2:
        flavor_ram: 1024
    vping_ssh:
        flavor_ram: 1024
    vping_userdata:
        flavor_ram: 1024
    cinder_test:
        flavor_ram: 1024
    tempest_smoke:
        flavor_ram: 1024
    tempest_neutron:
        flavor_ram: 1024
    refstack_compute:
        flavor_ram: 1024
    refstack_object:
        flavor_ram: 1024
    refstack_platform:
        flavor_ram: 1024
    patrole:
        flavor_ram: 1024
    vmtp:
        flavor_ram: 2048
    shaker:
        flavor_ram: 1024
    neutron_trunk:
        flavor_ram: 1024
    networking-bgpvpn:
        flavor_ram: 1024
    networking-sfc:
        flavor_ram: 1024
    barbican:
        flavor_ram: 1024
    tempest_full:
        flavor_ram: 1024
    tempest_scenario:
        flavor_ram: 1024
    rally_sanity:
        flavor_ram: 1024
    rally_full:
        flavor_ram: 1024
    rally_jobs:
        flavor_ram: 1024

vio:
    vmready1:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
    vmready2:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
    singlevm1:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
    singlevm2:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
    vping_ssh:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
    vping_userdata:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
    cinder_test:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
    tempest_smoke:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    tempest_neutron:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    refstack_compute:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    refstack_object:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    refstack_platform:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    patrole:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    vmtp:
        image:
            /home/opnfv/functest/images/ubuntu-14.04-server-cloudimg-amd64-disk1.vmdk
        image_format: vmdk
    shaker:
        image: /home/opnfv/functest/images/shaker-image.vmdk
        image_format: vmdk
    neutron_trunk:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    networking-bgpvpn:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    networking-sfc:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    barbican:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    tempest_full:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    tempest_scenario:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_alt_format: vmdk
    rally_sanity:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
    rally_full:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
    rally_jobs:
        image: /home/opnfv/functest/images/cirros-0.4.0-x86_64-disk.vmdk
        image_format: vmdk
    cloudify:
        image:
            /home/opnfv/functest/images/ubuntu-16.04-server-cloudimg-amd64-disk1.vmdk
        image_format: vmdk
    cloudify_ims:
        image:
            /home/opnfv/functest/images/ubuntu-16.04-server-cloudimg-amd64-disk1.vmdk
        image_format: vmdk
        image_alt:
            /home/opnfv/functest/images/ubuntu-14.04-server-cloudimg-amd64-disk1.vmdk
        image_alt_format: vmdk
    heat_ims:
        image:
            /home/opnfv/functest/images/ubuntu-14.04-server-cloudimg-amd64-disk1.vmdk
        image_format: vmdk
    vyos_vrouter:
        image:
            /home/opnfv/functest/images/ubuntu-16.04-server-cloudimg-amd64-disk1.vmdk
        image_format: vmdk
        image_alt: /home/opnfv/functest/images/vyos-1.1.7.vmdk
        image_alt_format: vmdk
    juju_epc:
        image:
            /home/opnfv/functest/images/ubuntu-16.04-server-cloudimg-amd64-disk1.vmdk
        image_format: vmdk
        image_alt:
            /home/opnfv/functest/images/ubuntu-14.04-server-cloudimg-amd64-disk1.vmdk
        image_alt_format: vmdk
