---
- hosts:
    - 127.0.0.1
  roles:
    - role: collivier.xtesting
      project: functest
      gerrit_project: functest
      builds:
        dependencies:
          - repo: _
            dport:
            container: alpine
            tag: 3.8
        steps:
          - name: build opnfv/functest-core
            containers:
              - name: functest-core
                ref_arg: BRANCH
                path: docker/core
          - name: build opnfv/functest-tempest
            containers:
              - name: functest-tempest
                ref_arg: BRANCH
                path: docker/tempest
          - name: build containers
            containers:
              - name: functest-healthcheck
                ref_arg: BRANCH
                path: docker/healthcheck
              - name: functest-smoke
                ref_arg: BRANCH
                path: docker/smoke
              - name: functest-benchmarking
                ref_arg: BRANCH
                path: docker/benchmarking
              - name: functest-components
                ref_arg:
                path: docker/components
              - name: functest-vnf
                ref_arg:
                path: docker/vnf
              - name: functest-features
                ref_arg: BRANCH
                path: docker/features
      suites:
        - container: functest-healthcheck
          tests:
            - connection_check
            - tenantnetwork1
            - tenantnetwork2
            - vmready1
            - vmready2
            - singlevm1
            - singlevm2
            - vping_ssh
            - vping_userdata
            - cinder_test
            - odl
            - api_check
            - snaps_health_check
        - container: functest-smoke
          tests:
            - tempest_smoke
            - neutron-tempest-plugin-api
            - rally_sanity
            - rally_jobs
            - refstack_defcore
            - patrole
            - snaps_smoke
            - neutron_trunk
            - networking-bgpvpn
            - networking-sfc
            - barbican
        - container: functest-benchmarking
          tests:
            - vmtp
            - shaker
        - container: functest-components
          tests:
            - tempest_full
            - tempest_scenario
            - rally_full
        - container: functest-vnf
          tests:
            - cloudify
            - cloudify_ims
            - heat_ims
            - vyos_vrouter
            - juju_epc
        - container: functest-features
          tests:
            - doctor-notification
            - bgpvpn
            - functest-odl-sfc
            - barometercollectd
            - vgpu
            - stor4nfv_os
